### PR TITLE
FIX: Floating point precision errors when applying debits/credits

### PR DESCRIPTION
**Pull request by lumberj**
Uses bignumber.js

```js
> 94.9899 - 5.0101
89.97980000000001
```

vs.

```js
> (new Bignumber(94.9899)).minus(5.0101).toNumber()
89.9798
```

### CODE REVIEW

**Comment by lumberj** [comment]
@clark800 @MatthewPhinney

**Comment by MatthewPhinney** [comment]
Nice use of the lodash api. To be clear, `sum()` and `difference()` return `Bignumber`, which is then written to the db as a js `Number`?

**Comment by lumberj** [comment]
> Nice use of the lodash api. To be clear, sum() and difference() return Bignumber, which is then written to the db as a js Number?

No they written a Number. This is still a problem if we have numbers with more than 15 significant digits though...

**Comment by lumberj** [comment]
Also, the tests don't pass because the CI database is using 2 decimal point precision, and sqlite doesn't enforce any. We are going to need to think about rounding rules. Closing this so we can discuss that first.

**Pull request closed without merging**
