### PR TITLE
Add `npm version` pre and post tasks for release

### PR DESCRIPTION
**Pull request by lumberj**
Use `npm version {patch|minor|major}` to release new version

https://docs.npmjs.com/cli/version

### CODE REVIEW

**Comment by MatthewPhinney** [comment]
LGTM

**Comment by clark800** [comment]
I was thinking this should be done in the CI script right after it finishes deployment. It looks like this method will push tags that aren't even valid yet?

**Comment by lumberj** [comment]
> It looks like this method will push tags that aren't even valid yet?

What do you mean by valid?

**Comment by clark800** [comment]
If you push the tags before pushing the new commits to master won't the tags be invalid?

**Comment by lumberj** [comment]
`npm version` should be run on master

**Comment by lumberj** [comment]
Whenever a new version is released, a version bump should be committed to master, tagged, and pushed. `npm version` does those steps now

**Comment by clark800** [comment]
Oh, `--follow-tags` pushes the code changes too right?

**Comment by lumberj** [comment]
Yes

**Comment by lumberj** [comment]
Related, for notary, https://github.com/interledger/five-bells-notary/pull/32

**Pull request merged**
