### PR TITLE
Revert ws dependency version due to conflict with koa-websocket depen…

### PR DESCRIPTION
**Pull request by clark800**
…dency

### CODE REVIEW

**Comment by emschwartz** [comment]
Is there a specific bug the version conflict causes? Since the ws update to [`v1.0.1` fixes a DoS vulnerability](https://github.com/websockets/ws/releases/tag/1.0.1) it would be good to update to this ASAP

**Comment by clark800** [comment]
Yeah, the publish script fails. I don't think DoS is a concern because this is a devDependency.

**Comment by emschwartz** [comment]
You're right that ws is only a devDependency but there is a DoS concern because the ledger uses `koa-websocket`, which depends on a DoS-able version of `ws`. I just opened an [issue](https://github.com/kudos/koa-websocket/issues/11) there but until that's updated I believe this vulnerability will affect the ledger.

**Comment by gip** [comment]
LGTM

**Comment by clark800** [comment]
@emschwartz That's true, thanks for opening the issue

**Pull request merged**
