### PR TITLE
[TEST] Run integration test module.

### PR DESCRIPTION
**Pull request by sentientwaffle**
Requires interledger/five-bells-integration-test#3

### CODE REVIEW

**Comment by geertweening** [comment]
`CircleCI` output says ```Nothing bad happened. But I also didn't test anything.``` Are we missing something. I'm going to rebuild so it might pick up the latest version of the integration-test

**Comment by sentientwaffle** [comment]
It was using an old version of five-bells-integration, but even now its not ready to merge -- circleCI is caching the dependencies too aggressively, which causes things not to work as expected. I'm working on a fix.

**Comment by clark800** [comment]
@sentientwaffle Did you try "Rebuild without cache" in the CircleCI console?

**Comment by sentientwaffle** [comment]
Ok, its fixed. The issue wasn't the cache, it was the branch grouping feature working unexpectedly.

**Comment by clark800** [comment]
It looks like the integration test logging is very verbose; it's hard to see what tests are being run. Is there any way to make the debug logging only appear for failed tests?

**Comment by sentientwaffle** [comment]
If it bugs you create an issue on interledger/five-bells-integration-test -- I don't think its worth blocking this PR for.

**Comment by clark800** [comment]
Ok, I added an issue. LGTM

**Pull request merged**
