### PR TITLE
Add /transfers/:id/fulfillment endpoint

### PR DESCRIPTION
**Pull request by clark800**
There will be more refactoring in the future to split the prepare and fulfillment logic into separate methods in the model, but this should be enough to get something working with the new notary API.

### CODE REVIEW

**Comment by emschwartz** [comment]
What's the point of having this endpoint if it is just going to pass it to the same controller as `PUT /transfers/:id`?

**Comment by clark800** [comment]
This is what the spec requires. The functionality can be split later as described in the description.

**Comment by emschwartz** [comment]
If you say so. A problem I could see arising with this is that if you don't submit the whole transfer exactly as it is in the db it'll give you an invalid modification error

**Comment by clark800** [comment]
> A problem I could see arising with this

Are you referring to this pull request or a pre-existing problem with the code?

**Comment by MatthewPhinney** [comment]
So this is what we need to be compatible with the new notary design? I don't see this endpoint in the ledger tech docs. I do see it, however, in the notary docs. What spec are you referring to?

**Comment by emschwartz** [comment]
With this, if you post the "fulfillment" I'd sort of expect it to just expect and care about the fulfillment. With this endpoint it will look at the whole transfer and return an error if the other fields aren't exactly what the ledger has in the db

**Comment by clark800** [comment]
Actually it sounds like the spec changed or is different than what I had thought: it is only putting the fulfillment part, so this will require more changes.

**Comment by emschwartz** [comment]
Gotcha, that makes more sense to me

**Comment by clark800** [comment]
Replaced by https://github.com/interledger/five-bells-ledger/pull/129

**Pull request closed without merging**
