### PR TITLE
Feature/logging

### PR DESCRIPTION
**Pull request by lumberj**
```shell
Projects/five-bells-ledger [feature/logging] » LEDGER_LOG_LEVEL=trace LEDGER_DB_URI=sqlite:// LEDGER_DB_SYNC=true npm start

> five-bells-ledger@15.1.0 start /Users/alan/Projects/five-bells-ledger
> node src/app.js | bunyan

Using autogenerated keys for notification signing.
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
[2016-07-19T21:23:14.998Z] DEBUG: ledger/66527 on alan-lm: checking for transfers to expire (module="expiry monitor")
[2016-07-19T21:23:15.042Z]  INFO: ledger/66527 on alan-lm: ledger listening on 0.0.0.0:3000 (module=app)
[2016-07-19T21:23:15.042Z]  INFO: ledger/66527 on alan-lm: public at http://alan-lm:3000 (module=app)
[2016-07-19T21:23:30.875Z]  INFO: ledger/66527 on alan-lm:   <-- GET / (req_id=60f097e8-32ce-4eb3-b891-b56054358b3a, module=app, query={})
    headers: {
      "host": "localhost:3000",
      "user-agent": "curl/7.43.0",
      "accept": "*/*"
    }
[2016-07-19T21:23:30.892Z]  INFO: ledger/66527 on alan-lm:   --> GET / 200 17ms (req_id=60f097e8-32ce-4eb3-b891-b56054358b3a, module=app, duration=17, status=200)
    headers: {
      "host": "localhost:3000",
      "user-agent": "curl/7.43.0",
      "accept": "*/*"
    }
    --
    body: {
      "currency_code": null,
      "currency_symbol": null,
      "condition_sign_public_key": "bNoCG7C1/uZ8eOMjl0cU4vHO9gO73VTd0LApvAS8YoY=",
      "notification_sign_public_key": "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAm+pRs22AJvA1fOneL5kLpGeX2pXuF9VM9SQ6CaDfrBEOvNcLScGD7J5V+SW0\n36PEywo1LByZ9UNbRv6wAcgcGVzxFtCecuSCDA4HCg69A+c29Lle0dL49pwQ+Dq6XtuqI3Hx\nYZfQnVzq5b2l8Q6YFFBGTw1Zfagy4VkzSSuDXHz39x2hySubuiKtvtvt20VeNBfqR8I1cbeO\n2uo0Rzki69Wo2oI+MIMNzZEq6ubNp5ixSlPl5aS6kGVjEcEOvgBnX8Nd8ChWvFyEkH7drOtk\ngs92kMIRimO2+MN4s46nu2PWzO1hWDdBLI7xHUbZJDabuIN4lFKxlio0T97T6TmRrwIDAQAB\n-----END RSA PUBLIC KEY-----\n",
      "urls": {
        "health": "http://alan-lm:3000/health",
        "transfer": "http://alan-lm:3000/transfers/:id",
        "transfer_fulfillment": "http://alan-lm:3000/transfers/:id/fulfillment",
        "transfer_state": "http://alan-lm:3000/transfers/:id/state",
        "connectors": "http://alan-lm:3000/connectors",
        "accounts": "http://alan-lm:3000/accounts",
        "account": "http://alan-lm:3000/accounts/:name",
        "subscription": "http://alan-lm:3000/subscriptions/:id",
        "subscription_notification": "http://alan-lm:3000/subscriptions/:subscription_id/notifications/:notification_id"
      },
      "precision": 10,
      "scale": 2
    }
```

### CODE REVIEW

**Comment by clark800** [comment]
LGTM

**Comment by lumberj** [comment]
Tests still not working

**Comment by lumberj** [comment]
Ok tests now working

**Comment by lumberj** [comment]
I need to make this a separate PR apparently

**Pull request closed without merging**
