### PR TITLE
[FIX] Allow scale=4

### PR DESCRIPTION
**Pull request by sentientwaffle**

### CODE REVIEW

**Comment by emschwartz** [comment]
What happens if `LEDGER_AMOUNT_SCALE` is larger than the value hard-coded in the database creation?

**Comment by sentientwaffle** [comment]
Then it will be broken, same as before. I needed scale=4 to work because the integration tests use it.

**Comment by MatthewPhinney** [comment]
I know @lumberj put in #215 to allow the ledger to have configurable precision. Might be good for him to take a quick look. Also, I'm curious what broke the integration tests? Why do they need scale=4?

**Comment by sentientwaffle** [comment]
The integration tests were written for scale=4. Fixing the ledger to (correctly) support it is simpler than rewriting the tests.

**Comment by gip** [comment]
Why are we hardcoding the scale? Ideally scale should be coming from configuration when creating the tables too.

**Comment by sentientwaffle** [comment]
I agree, but that's out of the scope of this PR.

**Comment by clark800** [comment]
LGTM after tests pass

**Pull request merged**
