### PR TITLE
Docs: document LEDGER_ILP_PREFIX field

### PR DESCRIPTION
**Pull request by bensharaf**
resolves https://github.com/interledger/five-bells-ledger/issues/317

### CODE REVIEW

**Comment by emschwartz** [comment]
LGTM. Build is failing because the integration tests are broken for other reasons. That's being looked into separately

**Comment by sentientwaffle** [comment]
Can you rebase this onto master so that the FTs pass?

**Comment by bensharaf** [comment]
rebased

**Comment by sentientwaffle** [comment]
LGTM

**Pull request merged**
